### PR TITLE
fix: createAuctionV2 scheme

### PR DESCRIPTION
**Pull request by dkchv**

### CODE REVIEW

**Comment by kurpav** [comment]
@dkchv 
What is the purpose of this PR?
The proposed schema is different from what is defined in the Rust smart contract

**Comment by dkchv** [comment]
@kurpav 
Struct defined in program here: https://github.com/metaplex-foundation/metaplex/blob/master/rust/auction/program/src/processor/create_auction_v2.rs#L29

Current scheme serializes `instantSale` and `name` params only and avoid rest of params (`end_auction_at`, `winners`, etc).

Fix PR fixes that difference.

**Comment by kurpav** [comment]
@dkchv 
ok, then I don't see `instantSale` and `name` params in the PR schema changes

**Comment by dkchv** [comment]
@kurpav 
My bad. Params added.

**Review by kurpav — APPROVED** [review]

**Pull request merged**
